sudo: required
services:
  - docker
before_install:
  - docker build -f Dockerfile.dev -t cameron/docker-react .

script:
  - docker run -e CI=true cameron/docker-react npm run test -- --coverage